name: 'Wodby deploy'
description: 'Handles a deploy on a Wodby app instance'
icon: arrow-up-circle
color: blue
inputs:
  uuid:
    description: 'Instance UUID (provided by Wodby)'
    required: true
  path:
    description: 'Base path to build'
    required: true
    default: './'
runs:
  using: "composite"
  steps:
  - run: wget -qO- https://api.wodby.com/api/v1/get/cli | sh
    shell: bash
  - run: echo $WODBY_API_KEY
    shell: bash
  - run: wodby ci init ${{ inputs.uuid }}.
    shell: bash
  - run: wodby ci build --from ${{ inputs.path }}.
    shell: bash
  - run: wodby ci release
    shell: bash
  - run: wodby ci deploy
    shell: bash
